/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.JavaFundamentals.basiclibrary.lib.src.test.java;

import com.JavaFundamentals.basiclibrary.lib.src.main.java.Lab02;
import com.JavaFundamentals.basiclibrary.lib.src.main.java.Lab03;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.HashSet;
import java.util.Iterator;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    Lab02 test02;
    Lab03 test03;
    @BeforeEach
    void setUp() {

        test02 = new Lab02();
        test03 = new Lab03();

    }


    @Test
    @DisplayName("Roll")
    void rollTest() {

        int n = 5;
        int n1 = 4;
        int n2 = 7;

        int[] testResult = test02.roll(n);
        int[] testResult1 = test02.roll(n1);
        int[] testResult2 = test02.roll(n2);


        assertArrayEquals(testResult, testResult);
        assertArrayEquals(testResult1, testResult1);
        assertArrayEquals(testResult2, testResult2);
    }

    @Test
    @DisplayName("Calculating Averages Test")
    void CalculatingAveragesTest() {


        int[] arr = {90, 80, 50, 70, 90, 95, 85, 79};
        int[] arr1 = {90, 60, 50, 70, 50, 95, 85, -50};
        int[] arr2 = {100, 100, 100, 99, 99, 95, 99, 99};

        int testResult = test02.CalculatingAverages(arr);
        int testResult1 = test02.CalculatingAverages(arr1);
        int testResult2 = test02.CalculatingAverages(arr2);

        assertEquals(79, testResult, "Your answer is wrong please double-check");
        assertEquals(56, testResult1, "Your answer is wrong please double-check");
        assertEquals(98, testResult2, "Your answer is wrong please double-check");
    }

    @Test
    @DisplayName("Contains Duplicates")
    void containsDuplicatesTest() {

        int[] arr = {90, 80, 50, 70, 92, 95, 85, 79};
        int[] arr1 = {90, 60, 50, 70, 50, 91, 85, -50};
        int[] arr2 = {100, 100, 100, 99, 99, 95, 99, 99};

        boolean testResult = test02.containsDuplicates(arr);
        boolean testResult1 = test02.containsDuplicates(arr1);
        boolean testResult2 = test02.containsDuplicates(arr2);

        assertFalse(testResult, "Your answer is wrong please double-check");
        assertTrue(testResult1, "Your answer is wrong please double-check");
        assertTrue(testResult2, "Your answer is wrong please double-check");
    }


    @Test
    @DisplayName("Arrays Of Arrays")
    void arraysOfArraysTest() {


        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {80, 54, 70, 53, 59, 57, 70},
                {65, 56, 55, 52, 55, 62, 57}
        };

        int[] testResult = test02.arraysOfArrays(weeklyMonthTemperatures);
        int[] arr = {65, 56, 55, 52, 55, 62, 57};
        assertArrayEquals(arr, testResult);
    }



}
