
package com.JavaFundamentals.basiclibrary.lib.src.main.java;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class Library {
    public static void main(String[] args) {

    }



}
