
package com.JavaFundamentals.basiclibrary.lib.src.main.java;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.*;
import java.util.*;

public class Library {
















}

//
//    Lab03 test = new Lab03();
//        int[][] weeklyMonthTemperatures = {
//                {66, 64, 58, 65, 71, 57, 60},
//                {57, 65, 65, 70, 72, 65, 51},
//                {55, 54, 60, 53, 59, 57, 61},
//                {65, 56, 55, 52, 55, 62, 57}
//        };
//
//        System.out.println(test.AnalyzingWeatherData(weeklyMonthTemperatures));
//


//    ArrayList<String> votes = new ArrayList<>();
//        votes.add("Bush");
//                votes.add("Bush");
//                votes.add("Bush");
//                votes.add("Shrub");
//                votes.add("Hedge");
//                votes.add("Shrub");
//                votes.add("Bush");
//                votes.add("Hedge");
//                votes.add("Bush");
//                votes.add("Shrub");
//                votes.add("Shrub");
//                votes.add("Shrub");
//                votes.add("Shrub");
//                votes.add("Shrub");
//                String s = test.tally(votes);
//                System.out.println(s);