/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.JavaFundamentals.linter.app.src.main.java.linter;
import java.io.*;
import java.util.Scanner;


public class App {


    public static void main(String[] args) throws FileNotFoundException {
        File read = new File("gates.js");
        //Scanner scan = new Scanner(read);
        System.out.println(read.canRead());
        System.out.println(read.canWrite());
        System.out.println(read.exists());
        System.out.println(read.getName());
        System.out.println(read.getAbsolutePath());
        System.out.println(read.length());

    }
}
