/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.JavaFundamentals.linter.app.src.test.java.linter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {


}
