/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.JavaFundamentals.inheritance.lib.src.main.java.inheritance;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {

        Scanner input = new Scanner(System.in);

        Restaurant shawerma = new Restaurant("Shanab",(byte) 2,"$");
        System.out.println(shawerma);

        // This section for task 3
//        System.out.println("One minute please, Rate us");
//        System.out.println("A small description, Tell us your experience");
//        String RevDesc = input.nextLine();
//        System.out.println("Your Name?");
//        String RevAuth = input.nextLine();
//        boolean correctRate = true;
//        byte RevStar = 0;
//        while (correctRate){
//            System.out.println("How likely are you to recommend "+ shawerma.name + " to a friend (0-5)");
//            RevStar = input.nextByte();
//            if(RevStar <= 5 && RevStar >= 0){
//                break;
//            }
//            else {
//                System.out.println("Please enter value between 0-5");
//                correctRate = true;
//            }
//        }
//
//        Review review = new Review(shawerma.name,RevDesc,RevAuth,RevStar);
//        System.out.println(review);


        //This section for 3rd task
        System.out.println("One minute please, Rate us");
        System.out.println("A small description, Tell us your experience");
        String RevDesc = input.nextLine();
        System.out.println("Your Name?");
        String RevAuth = input.nextLine();
        boolean correctRate = true;
        byte RevStar = 0;
        while (correctRate){
            System.out.println("How likely are you to recommend "+ shawerma.name + " to a friend (0-5)");
            shawerma.addReview(input.nextByte());//call add review method and pass the input for it
            if(RevStar <= 5 && RevStar >= 0){
                break;
            }
            else {
                System.out.println("Please enter value between 0-5");
                correctRate = true;
            }
        }

        Review review = new Review(shawerma.name,RevDesc,RevAuth,shawerma.star);
        System.out.println(review);




    }
}
