/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.JavaFundamentals.inheritance.lib.src.main.java.inheritance;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {

        Scanner input = new Scanner(System.in);


        // This section for task 1 and two (Test classes)
//        Restaurant shawerma = new Restaurant("Shanab", 2,"$");
//        System.out.println(shawerma);
//
//        Review reviewTest = new Review("very good restaurant","Mohammad ghanem",4);
//        System.out.println(reviewTest);



        //This section for 3rd, 4th and 5th tasks

          Restaurant shawerma = new Restaurant("Shanab", 2,"$");
        int RevStar = 0;
        while (true){
            System.out.println("One minute please, Rate us");
            System.out.println("A small description, Tell us your experience");
            String RevDesc = input.next();
            System.out.println("Your Name?");
            String RevAuth = input.next();
            System.out.println("How likely are you to recommend "+ shawerma.name + " to a friend (0-5)");
            RevStar = input.nextByte();
            //call add review method and pass the input for it
            if(RevStar <= 5 && RevStar >= 0){
                shawerma.addReview(RevDesc,RevAuth,RevStar);
                System.out.println(shawerma.toString());
            }
            else {
                System.out.println("Please enter value between 0-5");
            }

        }




    }
}
