/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.JavaFundamentals.inheritance.lib.src.main.java.inheritance;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {

        Scanner input = new Scanner(System.in);


        Theater movie = new Theater("Spider Man");

                  movie.addMovie("Spider man");
                  movie.addMovie("Batman");
                  movie.addMovie("Mask man");
                  movie.addMovie("Fireman");
                  //movie.removeMovie();
                  movie.addReview();
                  System.out.println(movie);


    }
}

//////////////////////////////////////////LAB06\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

    //This section for task 1 and two (Test classes)
//    Restaurant shawerma = new Restaurant("Shanab", 2,"$");
//        System.out.println(shawerma);
//
//                Review review = new Review("very good restaurant","Mohammad ghanem",4);
//                System.out.println(review);
//
//
//                //This section for 3rd, 4th and 5th tasks
//                int userEnd = 0;
//
//                while (userEnd != -1) {
//
//                shawerma.addReview();
//                System.out.println(shawerma);
//                System.out.println("Enter -1 to exit or press 0 to add another review");
//                userEnd = input.nextInt();
//                }


//////////////////////////////////////////LAB07\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

//   this section for 1 and 2 tasks
//    Restaurant restaurant = new Restaurant("Shanab", 4, "$");
//    Shop shop = new Shop("City Mall", "Amazing and very big mall and have multiple sections", 5, "$$$");
//
//
//        while (true) {
//                System.out.println("One minute please, Rate us\nPlease enter 1 to review restaurant and 2 to review shop or 3 to exit and show all Reviews");
//                int userSelect = input.nextInt();
//
//                if (userSelect == 1) {
//                restaurant.addReview();
//                System.out.println(restaurant);
//
//                } else if (userSelect == 2) {
//                shop.addReview();
//                System.out.println(shop);
//                } else if (userSelect == 3) {
//                break;
//                } else {
//                System.out.println("Sorry, you entered wrong number");
//                }
//                }
//                System.out.println("All Restaurant Reviews\n" + restaurant.getRestaurantReviews());
//                System.out.println("All Shop Reviews\n" + shop.getShopReviews());

//                this section for 3rd and 4th tasks
//                  Theater movie = new Theater();
//
//                  movie.addMovie("Spider man");
//                  movie.addMovie("Batman");
//                  movie.addMovie("Mask man");
//                  movie.addMovie("Fireman");
//                  movie.removeMovie();
//                  System.out.println(movie);