/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.JavaFundamentals.inheritance.lib.src.test.java.inheritance;

import com.JavaFundamentals.inheritance.lib.src.main.java.inheritance.Restaurant;
import com.JavaFundamentals.inheritance.lib.src.main.java.inheritance.Review;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class AppTest {
    Restaurant restaurant = new Restaurant("Test" ,0, "$$$" );
    Review review = new Review("very delicious meals","Mohammad Ghanem",5);


    @Test
    @DisplayName("Restaurant Constructor test")
    void testToStringRestaurant() { //Test that your Restaurant constructor is behaving reasonably.
        String ans =restaurant.toString();
        String expectedAns = "Restaurant{name='Test', stars= 0.0, priceCategory='$$$', reviews=[]', Number of reviews=0}";
        assertEquals(expectedAns,ans);

    }

    @Test
    @DisplayName("Review Constructor test")
    void testToStringReview() {  //Test that your constructor is working reasonably.
        String ans =review.toString();
        String expectedAns = "Review{review Body='very delicious meals', review Author='Mohammad Ghanem', review Stars=5}";
        assertEquals(expectedAns,ans);
    }



    @Test void addReviewTest () {
        restaurant.addReview("very clean restaurant","Mohammad ghaenm",4);
        restaurant.addReview("very good looking","Ghanem",2);
        String ans =restaurant.toString();
        String expectedAns = "Restaurant{name='Test', stars= 3.0, priceCategory='$$$', reviews=[Review{review Body='very clean restaurant', review Author='Mohammad ghaenm', review Stars=4}, Review{review Body='very good looking', review Author='Ghanem', review Stars=2}]', Number of reviews=2}";
        assertEquals(expectedAns,ans);

    }
}
